name: riverpod_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  riverpod_generator: ^2.1.4
  # riverpod_lint、custom_lintをインストールすることで、riverpod関係の開発アシストが可能になるはずだが出来ない。。
  riverpod_lint: ^1.1.6
  custom_lint: ^0.3.2

flutter:
  uses-material-design: true

analyzer:
  plugins:
    - custom_lint
